format shortE;

indiceNormalFinalDeVolta_NAONORM = [
indiceNormalidade(resultadosNormalizados.quaternion(indexFim.volta1,:)),...
indiceNormalidade(resultadosNormalizados.quaternion(indexFim.volta2,:)),...
indiceNormalidade(resultadosNormalizados.quaternion(indexFim.volta3,:)),...
indiceNormalidade(resultadosNormalizados.quaternion(indexFim.volta4,:))...
]*180/pi*3600;

indiceNormalFinalDeVolta_NORM = [
indiceNormalidade(resultadosNaoNormalizados.quaternion(indexFim.volta1,:)),...
indiceNormalidade(resultadosNaoNormalizados.quaternion(indexFim.volta2,:)),...
indiceNormalidade(resultadosNaoNormalizados.quaternion(indexFim.volta3,:)),...
indiceNormalidade(resultadosNaoNormalizados.quaternion(indexFim.volta4,:))...
]*180/pi*3600;

comparacaoIndicesNormalidade = indiceNormalFinalDeVolta_NORM - indiceNormalFinalDeVolta_NAONORM

%%

indiceDesalFinalDeVolta_NAONORM = [
indiceDesalinhamento(resultadosNormalizados.quaternion(indexFim.volta1,:), q0_base3),...
indiceDesalinhamento(resultadosNormalizados.quaternion(indexFim.volta2,:), q0_base3),...
indiceDesalinhamento(resultadosNormalizados.quaternion(indexFim.volta3,:), q0_base3),...
indiceDesalinhamento(resultadosNormalizados.quaternion(indexFim.volta4,:), q0_base3)...
]*180/pi*3600;

indiceDesalFinalDeVolta_NORM = [
indiceDesalinhamento(resultadosNaoNormalizados.quaternion(indexFim.volta1,:), q0_base3),...
indiceDesalinhamento(resultadosNaoNormalizados.quaternion(indexFim.volta2,:), q0_base3),...
indiceDesalinhamento(resultadosNaoNormalizados.quaternion(indexFim.volta3,:), q0_base3),...
indiceDesalinhamento(resultadosNaoNormalizados.quaternion(indexFim.volta4,:), q0_base3)...
]*180/pi*3600;

comparacaoIndicesDesalinhamento = indiceDesalFinalDeVolta_NORM - indiceDesalFinalDeVolta_NAONORM