function [matrix] = crossToMatrix(vector)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
a = vector(:);
matrix = [...
    0 -a(3) a(2);...
    a(3) 0 -a(1);...
    -a(2) a(1) 0 ...
    ];

end

