function R2L_writeheader(texfile,doktitle,dokauthor,opt_addheader)
% THIS IS PART OF REPORT2LATEX (R2L)
% 
% INPUTS:
% texfile      : complete path to the .tex file
% doktitle     : Document title (will be displayed in LATEX document).
% dokauthor    : Author (will be displayed in LATEX document).
% opt_addheader: Optional/additional header Text
% 
% OUTPUTS:
% none
% 
% FUNCTION:
% This function writes a new .tex file and adds a header. 
% CAUTION: If the file already exists it will be rewritten!
% 
% Jahn Ruehrig 2017

if nargin<4
    opt_addheader='';
end

CA1={'\documentclass[12pt]{report}';...
    strcat('\title{',doktitle,'}');...
    strcat('\author{',dokauthor,'}');...
    '\date{\today}';...
    '\usepackage[T1]{fontenc}';...
    '\usepackage[ansinew]{inputenc}';...
    '\usepackage[a4paper]{geometry}';...
    '\usepackage{graphicx}';...
    '\usepackage{amsbsy}';...
    '\usepackage{amstext}';...
    '\usepackage[cmex10]{amsmath}';...
    '\usepackage{array}';...
    '\usepackage{longtable}';...
    '\usepackage[nottoc,notlot,notlof]{tocbibind}';...
    '\usepackage[bf]{caption}';...
    '\usepackage{bigstrut}';...
    '\usepackage{multirow}';...
    '\usepackage[hang]{footmisc}';...
    '\setlength{\footnotemargin}{0.4cm}';...
    '\usepackage{float}';...
    '\usepackage[table]{xcolor}';...
    '\usepackage{setspace}';...
    '\usepackage[section]{placeins}';...
    '\usepackage{stfloats}';...
    '\usepackage{tabularx}';...
    '\usepackage{courier}';...
    '\usepackage{listings}';...
    '\usepackage[';...
     'colorlinks=false,';...
     'urlcolor=pdfurlcolor,';...
     'filecolor=pdffilecolor,';...
     'linkcolor=pdflinkcolor,';...
     'raiselinks=true,';...
     'breaklinks,';...
     'backref=page,';...
     'pagebackref=false,';...
     'verbose,';...
     'hyperindex=true,';...
     'linktocpage=true,';...
     'hyperfootnotes=false,';...
     'bookmarks=true,';...
     'bookmarksopen=true,';...
     'bookmarksopenlevel=\maxdimen,';...
     'bookmarksnumbered=true,';...
     'bookmarkstype=toc,';...
     'plainpages=false,';...
     'pageanchor=true,';...
     strcat('pdftitle=',doktitle,',');...
     'pdfauthor=AUTHOR'  %      strcat('pdfauthor=',dokauthor,',');...
     'pdfcreator={MATLAB},';...
     'pdfstartview=Fit,';...
     'pdfpagemode=UseOutlines,';...
     'pdfpagelabels=true,';...
     'pdfpagelayout=TwoPageRight,';...
     ']{hyperref}';...
    '\usepackage{cite}';...
    '\usepackage{tikz}';...
    '\usepackage[toc,page]{appendix}';...
    '\usepackage[ nonumberlist,acronym,toc,section]{glossaries}';...
    '\makenoidxglossaries';...
    '';
    '%%%%%%% OPTIONAL HEADER %%%%%%%%%%%%%';
    };
    
CA2={'%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%';    
    '\begin{document}';...
    };


CA=[CA1;opt_addheader;CA2];

    writeheader(texfile,CA);


end


function writeheader(texfile,CA)
%% WRITE THE HEADER TO A TEX FILE DELETING EVERYTHING THAT WAS THERE BEFORE

si=size(CA,1);

fid = fopen( texfile, 'wt' );
% fid = fopen( 'test.tex', 'a+' );

for cnt=1:si
    
    fprintf( fid, '%s \n', CA{cnt} );

end

fclose(fid);

end






