function [phi] = CASO3_erroAtitude(t,Omega,deriva)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
e = deriva;

phi = [...
    t 0 0; ...
    0 1/Omega*sin(Omega*t) 1/Omega*(1-cos(Omega*t)); ...
    0 -1/Omega*(1-cos(Omega*t)) 1/Omega*sin(Omega*t) ...
    ]*e;
end

